# Generated by Django 5.0.6 on 2024-07-18 08:45

from django.db import migrations
import openpyxl
from django.core.exceptions import ValidationError

def insert_airlines(apps, schema_editor):
    Airline = apps.get_model('parcel', 'Airline')
    
    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('parcel/data/kia.xlsx')
        sheet = wb['Airline']
        
        # Extract Airline names from the Excel sheet
        airlines_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            airline_name = row[0]  # Assuming Airline name is in the first column
            airlines_data.append({'airline_name': airline_name})
        
        # Insert data into the model
        for data in airlines_data:
            try:
                Airline.objects.create(**data)
            except ValidationError as e:
                print(f"Validation Error: {e}")
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_auto_20240718_1135'),
    ]

    operations = [
        migrations.RunPython(insert_airlines)
    ]
